/*
 * PetFeeder Gateway
 *
 * This is PBL VI main gateway
 *
 * API version: 1.2.0
 * Contact: isacartur@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PetRegisterRequestAllOf struct {

	// Plan UUID
	PlanUuid string `json:"plan_uuid,omitempty"`
}

// AssertPetRegisterRequestAllOfRequired checks if the required fields are not zero-ed
func AssertPetRegisterRequestAllOfRequired(obj PetRegisterRequestAllOf) error {
	return nil
}

// AssertRecursePetRegisterRequestAllOfRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PetRegisterRequestAllOf (e.g. [][]PetRegisterRequestAllOf), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePetRegisterRequestAllOfRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPetRegisterRequestAllOf, ok := obj.(PetRegisterRequestAllOf)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPetRegisterRequestAllOfRequired(aPetRegisterRequestAllOf)
	})
}
