/*
 * PetFeeder Gateway
 *
 * This is PBL VI main gateway
 *
 * API version: 1.2.0
 * Contact: isacartur@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ApiKey struct {

	// API key for Raspberry device
	Key string `json:"key,omitempty"`
}

// AssertApiKeyRequired checks if the required fields are not zero-ed
func AssertApiKeyRequired(obj ApiKey) error {
	return nil
}

// AssertRecurseApiKeyRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ApiKey (e.g. [][]ApiKey), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseApiKeyRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aApiKey, ok := obj.(ApiKey)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertApiKeyRequired(aApiKey)
	})
}
