/*
 * PetFeeder Gateway
 *
 * This is PBL VI main gateway
 *
 * API version: 1.2.0
 * Contact: isacartur@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PetSetPlanRequest struct {

	// Pet UUID
	PetUuid string `json:"pet_uuid,omitempty"`

	// Plan UUID
	PlanUuid string `json:"plan_uuid,omitempty"`
}

// AssertPetSetPlanRequestRequired checks if the required fields are not zero-ed
func AssertPetSetPlanRequestRequired(obj PetSetPlanRequest) error {
	return nil
}

// AssertRecursePetSetPlanRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PetSetPlanRequest (e.g. [][]PetSetPlanRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePetSetPlanRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPetSetPlanRequest, ok := obj.(PetSetPlanRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPetSetPlanRequestRequired(aPetSetPlanRequest)
	})
}
