/*
 * PetFeeder Gateway
 *
 * This is PBL VI main gateway
 *
 * API version: 1.2.0
 * Contact: isacartur@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PetRegisterRequest struct {

	// Name of the pet
	PetName string `json:"pet_name,omitempty"`

	// Pet UUID
	PetUuid string `json:"pet_uuid,omitempty"`

	// Plan UUID
	PlanUuid string `json:"plan_uuid,omitempty"`
}

// AssertPetRegisterRequestRequired checks if the required fields are not zero-ed
func AssertPetRegisterRequestRequired(obj PetRegisterRequest) error {
	return nil
}

// AssertRecursePetRegisterRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PetRegisterRequest (e.g. [][]PetRegisterRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePetRegisterRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPetRegisterRequest, ok := obj.(PetRegisterRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPetRegisterRequestRequired(aPetRegisterRequest)
	})
}
