/*
 * PetFeeder Gateway
 *
 * This is PBL VI main gateway
 *
 * API version: 1.2.0
 * Contact: isacartur@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UserRetrieveDevicesResponse struct {

	// Test array
	Devices []DeviceMetadata `json:"devices,omitempty"`
}

// AssertUserRetrieveDevicesResponseRequired checks if the required fields are not zero-ed
func AssertUserRetrieveDevicesResponseRequired(obj UserRetrieveDevicesResponse) error {
	for _, el := range obj.Devices {
		if err := AssertDeviceMetadataRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseUserRetrieveDevicesResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of UserRetrieveDevicesResponse (e.g. [][]UserRetrieveDevicesResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseUserRetrieveDevicesResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aUserRetrieveDevicesResponse, ok := obj.(UserRetrieveDevicesResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertUserRetrieveDevicesResponseRequired(aUserRetrieveDevicesResponse)
	})
}
