/*
 * PetFeeder Gateway
 *
 * This is PBL VI main gateway
 *
 * API version: 1.2.0
 * Contact: isacartur@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UserMetadata struct {

	// Name of the user
	UserName string `json:"user_name,omitempty"`

	// Number of active devices of the user
	DeviceNum int64 `json:"device_num,omitempty"`

	// Reserved for future fields
	Reserved string `json:"reserved,omitempty"`
}

// AssertUserMetadataRequired checks if the required fields are not zero-ed
func AssertUserMetadataRequired(obj UserMetadata) error {
	return nil
}

// AssertRecurseUserMetadataRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of UserMetadata (e.g. [][]UserMetadata), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseUserMetadataRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aUserMetadata, ok := obj.(UserMetadata)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertUserMetadataRequired(aUserMetadata)
	})
}
