/*
 * PetFeeder Gateway
 *
 * This is PBL VI main gateway
 *
 * API version: 1.2.0
 * Contact: isacartur@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Token struct {

	// HMAC JWT token
	Token string `json:"token,omitempty"`
}

// AssertTokenRequired checks if the required fields are not zero-ed
func AssertTokenRequired(obj Token) error {
	return nil
}

// AssertRecurseTokenRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Token (e.g. [][]Token), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseTokenRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aToken, ok := obj.(Token)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertTokenRequired(aToken)
	})
}
