/*
 * PetFeeder Gateway
 *
 * This is PBL VI main gateway
 *
 * API version: 1.2.0
 * Contact: isacartur@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Device struct {

	// Device which will be assigned to this pet
	DeviceUuid string `json:"device_uuid,omitempty"`
}

// AssertDeviceRequired checks if the required fields are not zero-ed
func AssertDeviceRequired(obj Device) error {
	return nil
}

// AssertRecurseDeviceRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Device (e.g. [][]Device), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDeviceRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDevice, ok := obj.(Device)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDeviceRequired(aDevice)
	})
}
